# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Xcode 16.2
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: List available iOS simulators
        run: xcrun simctl list devices

      - name: Build iOS app
        run: |
          xcodebuild \
            -project LoginDemoSiwiftUI/LoginDemoSiwiftUI.xcodeproj \
            -scheme LoginDemoSiwiftUI \
            -destination "platform=iOS Simulator,name=iPhone 16" \
            clean build
