# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Build and Archive

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Xcode 16.2
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Archive App (Device)
        run: |
          xcodebuild \
            -project LoginDemoSiwiftUI/LoginDemoSiwiftUI.xcodeproj \
            -scheme LoginDemoSiwiftUI \
            -configuration Release \
            -archivePath build/LoginDemoSiwiftUI.xcarchive \
            clean archive

      - name: Export .ipa
        run: |
          xcodebuild -exportArchive \
            -archivePath build/LoginDemoSiwiftUI.xcarchive \
            -exportPath build/export \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LoginDemoSiwiftUI.ipa
          path: build/export/*.ipa
