# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Build and Archive

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Xcode 16.2
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Find available iPhone simulator
        id: find-simulator
        run: |
          SIMULATOR=$(xcrun simctl list devices available | grep -m1 "iPhone 16" | awk -F '[()]' '{print $2}')
          echo "SIMULATOR_ID=$SIMULATOR" >> $GITHUB_OUTPUT

      - name: Build and archive app
        run: |
          mkdir -p build
          xcodebuild clean archive \
            -project LoginDemoSiwiftUI/LoginDemoSiwiftUI.xcodeproj \
            -scheme LoginDemoSiwiftUI \
            -destination "id=${{ steps.find-simulator.outputs.SIMULATOR_ID }}" \
            -archivePath build/LoginDemoSiwiftUI.xcarchive \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES

      - name: Export .ipa
        run: |
          xcodebuild -exportArchive \
            -archivePath build/LoginDemoSiwiftUI.xcarchive \
            -exportPath build/export \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LoginDemoSiwiftUI.ipa
          path: build/export/*.ipa
